<?php
/**
 * RoyalMailLabelFormatShipmentInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailLabelFormatShipmentInformation Class Doc Comment
 *
 * @category Class
 * @description Used to provide shipment-level information such as service code, content type, general goods description, total shipment weight and value etc.
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailLabelFormatShipmentInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailLabelFormatShipmentInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'action' => '\RoyalMailV4\ShipmentsApi\Model\CreateShipmentAction',
        'labelFormat' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormat',
        'contentType' => '\RoyalMailV4\ShipmentsApi\Model\ContentType',
        'serviceCode' => 'string',
        'descriptionOfGoods' => 'string',
        'businessTransactionType' => '\RoyalMailV4\ShipmentsApi\Model\BusinessTransactionType',
        'shipmentDate' => '\DateTime',
        'declaredValue' => 'double',
        'declaredWeight' => 'double',
        'currencyCode' => 'string',
        'weightUnitOfMeasure' => '\RoyalMailV4\ShipmentsApi\Model\WeightUnitOfMeasure',
        'dimensionsUnitOfMeasure' => '\RoyalMailV4\ShipmentsApi\Model\DimensionsUnitOfMeasure'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'action' => null,
        'labelFormat' => null,
        'contentType' => null,
        'serviceCode' => null,
        'descriptionOfGoods' => null,
        'businessTransactionType' => null,
        'shipmentDate' => 'date',
        'declaredValue' => 'double',
        'declaredWeight' => 'double',
        'currencyCode' => null,
        'weightUnitOfMeasure' => null,
        'dimensionsUnitOfMeasure' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'action' => 'Action',
        'labelFormat' => 'LabelFormat',
        'contentType' => 'ContentType',
        'serviceCode' => 'ServiceCode',
        'descriptionOfGoods' => 'DescriptionOfGoods',
        'businessTransactionType' => 'BusinessTransactionType',
        'shipmentDate' => 'ShipmentDate',
        'declaredValue' => 'DeclaredValue',
        'declaredWeight' => 'DeclaredWeight',
        'currencyCode' => 'CurrencyCode',
        'weightUnitOfMeasure' => 'WeightUnitOfMeasure',
        'dimensionsUnitOfMeasure' => 'DimensionsUnitOfMeasure'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'action' => 'setAction',
        'labelFormat' => 'setLabelFormat',
        'contentType' => 'setContentType',
        'serviceCode' => 'setServiceCode',
        'descriptionOfGoods' => 'setDescriptionOfGoods',
        'businessTransactionType' => 'setBusinessTransactionType',
        'shipmentDate' => 'setShipmentDate',
        'declaredValue' => 'setDeclaredValue',
        'declaredWeight' => 'setDeclaredWeight',
        'currencyCode' => 'setCurrencyCode',
        'weightUnitOfMeasure' => 'setWeightUnitOfMeasure',
        'dimensionsUnitOfMeasure' => 'setDimensionsUnitOfMeasure'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'action' => 'getAction',
        'labelFormat' => 'getLabelFormat',
        'contentType' => 'getContentType',
        'serviceCode' => 'getServiceCode',
        'descriptionOfGoods' => 'getDescriptionOfGoods',
        'businessTransactionType' => 'getBusinessTransactionType',
        'shipmentDate' => 'getShipmentDate',
        'declaredValue' => 'getDeclaredValue',
        'declaredWeight' => 'getDeclaredWeight',
        'currencyCode' => 'getCurrencyCode',
        'weightUnitOfMeasure' => 'getWeightUnitOfMeasure',
        'dimensionsUnitOfMeasure' => 'getDimensionsUnitOfMeasure'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['action'] = isset($data['action']) ? $data['action'] : null;
        $this->container['labelFormat'] = isset($data['labelFormat']) ? $data['labelFormat'] : null;
        $this->container['contentType'] = isset($data['contentType']) ? $data['contentType'] : null;
        $this->container['serviceCode'] = isset($data['serviceCode']) ? $data['serviceCode'] : null;
        $this->container['descriptionOfGoods'] = isset($data['descriptionOfGoods']) ? $data['descriptionOfGoods'] : null;
        $this->container['businessTransactionType'] = isset($data['businessTransactionType']) ? $data['businessTransactionType'] : null;
        $this->container['shipmentDate'] = isset($data['shipmentDate']) ? $data['shipmentDate'] : null;
        $this->container['declaredValue'] = isset($data['declaredValue']) ? $data['declaredValue'] : null;
        $this->container['declaredWeight'] = isset($data['declaredWeight']) ? $data['declaredWeight'] : null;
        $this->container['currencyCode'] = isset($data['currencyCode']) ? $data['currencyCode'] : null;
        $this->container['weightUnitOfMeasure'] = isset($data['weightUnitOfMeasure']) ? $data['weightUnitOfMeasure'] : null;
        $this->container['dimensionsUnitOfMeasure'] = isset($data['dimensionsUnitOfMeasure']) ? $data['dimensionsUnitOfMeasure'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['contentType'] === null) {
            $invalidProperties[] = "'contentType' can't be null";
        }
        if ($this->container['serviceCode'] === null) {
            $invalidProperties[] = "'serviceCode' can't be null";
        }
        if ($this->container['descriptionOfGoods'] === null) {
            $invalidProperties[] = "'descriptionOfGoods' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets action
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\CreateShipmentAction
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\CreateShipmentAction $action action
     *
     * @return $this
     */
    public function setAction($action)
    {
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets labelFormat
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormat
     */
    public function getLabelFormat()
    {
        return $this->container['labelFormat'];
    }

    /**
     * Sets labelFormat
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormat $labelFormat labelFormat
     *
     * @return $this
     */
    public function setLabelFormat($labelFormat)
    {
        $this->container['labelFormat'] = $labelFormat;

        return $this;
    }

    /**
     * Gets contentType
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\ContentType
     */
    public function getContentType()
    {
        return $this->container['contentType'];
    }

    /**
     * Sets contentType
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\ContentType $contentType contentType
     *
     * @return $this
     */
    public function setContentType($contentType)
    {
        $this->container['contentType'] = $contentType;

        return $this;
    }

    /**
     * Gets serviceCode
     *
     * @return string
     */
    public function getServiceCode()
    {
        return $this->container['serviceCode'];
    }

    /**
     * Sets serviceCode
     *
     * @param string $serviceCode The code of the shipping service used to deliver the shipment.
     *
     * @return $this
     */
    public function setServiceCode($serviceCode)
    {
        $this->container['serviceCode'] = $serviceCode;

        return $this;
    }

    /**
     * Gets descriptionOfGoods
     *
     * @return string
     */
    public function getDescriptionOfGoods()
    {
        return $this->container['descriptionOfGoods'];
    }

    /**
     * Sets descriptionOfGoods
     *
     * @param string $descriptionOfGoods A general description of the type of goods being sent.
     *
     * @return $this
     */
    public function setDescriptionOfGoods($descriptionOfGoods)
    {
        $this->container['descriptionOfGoods'] = $descriptionOfGoods;

        return $this;
    }

    /**
     * Gets businessTransactionType
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\BusinessTransactionType
     */
    public function getBusinessTransactionType()
    {
        return $this->container['businessTransactionType'];
    }

    /**
     * Sets businessTransactionType
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\BusinessTransactionType $businessTransactionType businessTransactionType
     *
     * @return $this
     */
    public function setBusinessTransactionType($businessTransactionType)
    {
        $this->container['businessTransactionType'] = $businessTransactionType;

        return $this;
    }

    /**
     * Gets shipmentDate
     *
     * @return \DateTime
     */
    public function getShipmentDate()
    {
        return $this->container['shipmentDate'];
    }

    /**
     * Sets shipmentDate
     *
     * @param \DateTime $shipmentDate The date the shipment packages will be shipped. <br />Shipment Date cannot be in the past and cannot be more than 28 days in the future. <br />Defaults to the current date if not populated. <br />Accepted Format: YYYY-MM-DD
     *
     * @return $this
     */
    public function setShipmentDate($shipmentDate)
    {
        $this->container['shipmentDate'] = $shipmentDate;

        return $this;
    }

    /**
     * Gets declaredValue
     *
     * @return double
     */
    public function getDeclaredValue()
    {
        return $this->container['declaredValue'];
    }

    /**
     * Sets declaredValue
     *
     * @param double $declaredValue The declared value of the total shipment in the currency specified. <br />If provided, the value must be equal to or greater than the sum of all item values. <br />If not provided it defaults to the sum of all item values. <br />Ignored for Non-Consignment Services where multiple packages are declared - use the Declared Value at package level instead.
     *
     * @return $this
     */
    public function setDeclaredValue($declaredValue)
    {
        $this->container['declaredValue'] = $declaredValue;

        return $this;
    }

    /**
     * Gets declaredWeight
     *
     * @return double
     */
    public function getDeclaredWeight()
    {
        return $this->container['declaredWeight'];
    }

    /**
     * Sets declaredWeight
     *
     * @param double $declaredWeight The declared weight of the total shipment in the unit of measure specified by WeightUnitOfMeasure (defaults to KG). <br />The minimum weight allowed is 1 gram. <br />The maximum weight is dependent on the carrier / service / destination. <br />The weight must be equal to or greater than the sum of all package weights and/or item weights. <br />Required for Consignment Services. <br />Ignored for Non-Consignment Services - use the Declared Weight at package level instead.
     *
     * @return $this
     */
    public function setDeclaredWeight($declaredWeight)
    {
        $this->container['declaredWeight'] = $declaredWeight;

        return $this;
    }

    /**
     * Gets currencyCode
     *
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->container['currencyCode'];
    }

    /**
     * Sets currencyCode
     *
     * @param string $currencyCode The currency code used for any monetary value related to the shipment. <br />3 letter ISO Currency Code. <br />*Required if any monetary values other than zero are provided.*
     *
     * @return $this
     */
    public function setCurrencyCode($currencyCode)
    {
        $this->container['currencyCode'] = $currencyCode;

        return $this;
    }

    /**
     * Gets weightUnitOfMeasure
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\WeightUnitOfMeasure
     */
    public function getWeightUnitOfMeasure()
    {
        return $this->container['weightUnitOfMeasure'];
    }

    /**
     * Sets weightUnitOfMeasure
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\WeightUnitOfMeasure $weightUnitOfMeasure weightUnitOfMeasure
     *
     * @return $this
     */
    public function setWeightUnitOfMeasure($weightUnitOfMeasure)
    {
        $this->container['weightUnitOfMeasure'] = $weightUnitOfMeasure;

        return $this;
    }

    /**
     * Gets dimensionsUnitOfMeasure
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\DimensionsUnitOfMeasure
     */
    public function getDimensionsUnitOfMeasure()
    {
        return $this->container['dimensionsUnitOfMeasure'];
    }

    /**
     * Sets dimensionsUnitOfMeasure
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\DimensionsUnitOfMeasure $dimensionsUnitOfMeasure dimensionsUnitOfMeasure
     *
     * @return $this
     */
    public function setDimensionsUnitOfMeasure($dimensionsUnitOfMeasure)
    {
        $this->container['dimensionsUnitOfMeasure'] = $dimensionsUnitOfMeasure;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
