<?php
/**
 * RoyalMailDataStreamDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailDataStreamDetails Class Doc Comment
 *
 * @category Class
 * @description DATASTREAM Details &lt;br /&gt;The information needed to create your own label. &lt;br /&gt;Only present if DATASTREAM label format was specified.
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailDataStreamDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailDataStreamDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'primary2DBarcodeImage' => 'string',
        'primary2DBarcodeData' => 'string',
        'formattedUniqueId' => 'string',
        'gazetteerCodes' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailGazetteerCodes',
        'primary1DBarcodeImage' => 'string',
        'primary1DBarcodeData' => 'string',
        'highVolumeBarcodeImage' => 'string',
        'highVolumeBarcodeData' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'primary2DBarcodeImage' => null,
        'primary2DBarcodeData' => null,
        'formattedUniqueId' => null,
        'gazetteerCodes' => null,
        'primary1DBarcodeImage' => null,
        'primary1DBarcodeData' => null,
        'highVolumeBarcodeImage' => null,
        'highVolumeBarcodeData' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'primary2DBarcodeImage' => 'Primary2DBarcodeImage',
        'primary2DBarcodeData' => 'Primary2DBarcodeData',
        'formattedUniqueId' => 'FormattedUniqueId',
        'gazetteerCodes' => 'GazetteerCodes',
        'primary1DBarcodeImage' => 'Primary1DBarcodeImage',
        'primary1DBarcodeData' => 'Primary1DBarcodeData',
        'highVolumeBarcodeImage' => 'HighVolumeBarcodeImage',
        'highVolumeBarcodeData' => 'HighVolumeBarcodeData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'primary2DBarcodeImage' => 'setPrimary2DBarcodeImage',
        'primary2DBarcodeData' => 'setPrimary2DBarcodeData',
        'formattedUniqueId' => 'setFormattedUniqueId',
        'gazetteerCodes' => 'setGazetteerCodes',
        'primary1DBarcodeImage' => 'setPrimary1DBarcodeImage',
        'primary1DBarcodeData' => 'setPrimary1DBarcodeData',
        'highVolumeBarcodeImage' => 'setHighVolumeBarcodeImage',
        'highVolumeBarcodeData' => 'setHighVolumeBarcodeData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'primary2DBarcodeImage' => 'getPrimary2DBarcodeImage',
        'primary2DBarcodeData' => 'getPrimary2DBarcodeData',
        'formattedUniqueId' => 'getFormattedUniqueId',
        'gazetteerCodes' => 'getGazetteerCodes',
        'primary1DBarcodeImage' => 'getPrimary1DBarcodeImage',
        'primary1DBarcodeData' => 'getPrimary1DBarcodeData',
        'highVolumeBarcodeImage' => 'getHighVolumeBarcodeImage',
        'highVolumeBarcodeData' => 'getHighVolumeBarcodeData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['primary2DBarcodeImage'] = isset($data['primary2DBarcodeImage']) ? $data['primary2DBarcodeImage'] : null;
        $this->container['primary2DBarcodeData'] = isset($data['primary2DBarcodeData']) ? $data['primary2DBarcodeData'] : null;
        $this->container['formattedUniqueId'] = isset($data['formattedUniqueId']) ? $data['formattedUniqueId'] : null;
        $this->container['gazetteerCodes'] = isset($data['gazetteerCodes']) ? $data['gazetteerCodes'] : null;
        $this->container['primary1DBarcodeImage'] = isset($data['primary1DBarcodeImage']) ? $data['primary1DBarcodeImage'] : null;
        $this->container['primary1DBarcodeData'] = isset($data['primary1DBarcodeData']) ? $data['primary1DBarcodeData'] : null;
        $this->container['highVolumeBarcodeImage'] = isset($data['highVolumeBarcodeImage']) ? $data['highVolumeBarcodeImage'] : null;
        $this->container['highVolumeBarcodeData'] = isset($data['highVolumeBarcodeData']) ? $data['highVolumeBarcodeData'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['primary2DBarcodeImage'] === null) {
            $invalidProperties[] = "'primary2DBarcodeImage' can't be null";
        }
        if ($this->container['primary2DBarcodeData'] === null) {
            $invalidProperties[] = "'primary2DBarcodeData' can't be null";
        }
        if ($this->container['formattedUniqueId'] === null) {
            $invalidProperties[] = "'formattedUniqueId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets primary2DBarcodeImage
     *
     * @return string
     */
    public function getPrimary2DBarcodeImage()
    {
        return $this->container['primary2DBarcodeImage'];
    }

    /**
     * Sets primary2DBarcodeImage
     *
     * @param string $primary2DBarcodeImage Primary 2D Barcode Image <br />Base64 Encoded PNG Image of the 2D data matrix barcode.
     *
     * @return $this
     */
    public function setPrimary2DBarcodeImage($primary2DBarcodeImage)
    {
        $this->container['primary2DBarcodeImage'] = $primary2DBarcodeImage;

        return $this;
    }

    /**
     * Gets primary2DBarcodeData
     *
     * @return string
     */
    public function getPrimary2DBarcodeData()
    {
        return $this->container['primary2DBarcodeData'];
    }

    /**
     * Sets primary2DBarcodeData
     *
     * @param string $primary2DBarcodeData Primary 2D Barcode Data - Base 64 Encoded <br />Data required to create your own 2D data matrix barcode. Please decode before use.
     *
     * @return $this
     */
    public function setPrimary2DBarcodeData($primary2DBarcodeData)
    {
        $this->container['primary2DBarcodeData'] = $primary2DBarcodeData;

        return $this;
    }

    /**
     * Gets formattedUniqueId
     *
     * @return string
     */
    public function getFormattedUniqueId()
    {
        return $this->container['formattedUniqueId'];
    }

    /**
     * Sets formattedUniqueId
     *
     * @param string $formattedUniqueId Formatted Unique Id <br />Label for 2D data matrix barcode.
     *
     * @return $this
     */
    public function setFormattedUniqueId($formattedUniqueId)
    {
        $this->container['formattedUniqueId'] = $formattedUniqueId;

        return $this;
    }

    /**
     * Gets gazetteerCodes
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailGazetteerCodes
     */
    public function getGazetteerCodes()
    {
        return $this->container['gazetteerCodes'];
    }

    /**
     * Sets gazetteerCodes
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailGazetteerCodes $gazetteerCodes gazetteerCodes
     *
     * @return $this
     */
    public function setGazetteerCodes($gazetteerCodes)
    {
        $this->container['gazetteerCodes'] = $gazetteerCodes;

        return $this;
    }

    /**
     * Gets primary1DBarcodeImage
     *
     * @return string
     */
    public function getPrimary1DBarcodeImage()
    {
        return $this->container['primary1DBarcodeImage'];
    }

    /**
     * Sets primary1DBarcodeImage
     *
     * @param string $primary1DBarcodeImage Primary 1D Barcode Image <br />Only populated where the service requires the barcode on the label. <br />Base64 Encoded PNG Image of the barcode.
     *
     * @return $this
     */
    public function setPrimary1DBarcodeImage($primary1DBarcodeImage)
    {
        $this->container['primary1DBarcodeImage'] = $primary1DBarcodeImage;

        return $this;
    }

    /**
     * Gets primary1DBarcodeData
     *
     * @return string
     */
    public function getPrimary1DBarcodeData()
    {
        return $this->container['primary1DBarcodeData'];
    }

    /**
     * Sets primary1DBarcodeData
     *
     * @param string $primary1DBarcodeData Primary 1D Barcode Data <br />Only populated where the service requires the barcode on the label. <br />Data required to create your own barcode.
     *
     * @return $this
     */
    public function setPrimary1DBarcodeData($primary1DBarcodeData)
    {
        $this->container['primary1DBarcodeData'] = $primary1DBarcodeData;

        return $this;
    }

    /**
     * Gets highVolumeBarcodeImage
     *
     * @return string
     */
    public function getHighVolumeBarcodeImage()
    {
        return $this->container['highVolumeBarcodeImage'];
    }

    /**
     * Sets highVolumeBarcodeImage
     *
     * @param string $highVolumeBarcodeImage High Volume Barcode Image <br />Only populated where the service (Tracked High Volume) requires the barcode on the label. <br />Base64 Encoded PNG Image of the barcode.
     *
     * @return $this
     */
    public function setHighVolumeBarcodeImage($highVolumeBarcodeImage)
    {
        $this->container['highVolumeBarcodeImage'] = $highVolumeBarcodeImage;

        return $this;
    }

    /**
     * Gets highVolumeBarcodeData
     *
     * @return string
     */
    public function getHighVolumeBarcodeData()
    {
        return $this->container['highVolumeBarcodeData'];
    }

    /**
     * Sets highVolumeBarcodeData
     *
     * @param string $highVolumeBarcodeData High Volume Barcode Data <br />Only populated where the service (Tracked High Volume) requires the barcode on the label. <br />Data required to create your own barcode.
     *
     * @return $this
     */
    public function setHighVolumeBarcodeData($highVolumeBarcodeData)
    {
        $this->container['highVolumeBarcodeData'] = $highVolumeBarcodeData;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
