<?php
/**
 * RoyalMailShipmentRequestCarrierSpecifics
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailShipmentRequestCarrierSpecifics Class Doc Comment
 *
 * @category Class
 * @description Royal Mail-specific features that can be used when creating a Royal Mail shipment.
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailShipmentRequestCarrierSpecifics implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailShipmentRequestCarrierSpecifics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'serviceLevel' => 'string',
        'ebayVtn' => 'string',
        'serviceEnhancements' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailServiceEnhancement[]',
        'offlineBarcode' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcode',
        'offlineBarcodes' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcode[]',
        'preAllocatedTrackingNumber' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'serviceLevel' => null,
        'ebayVtn' => null,
        'serviceEnhancements' => null,
        'offlineBarcode' => null,
        'offlineBarcodes' => null,
        'preAllocatedTrackingNumber' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'serviceLevel' => 'ServiceLevel',
        'ebayVtn' => 'EbayVtn',
        'serviceEnhancements' => 'ServiceEnhancements',
        'offlineBarcode' => 'OfflineBarcode',
        'offlineBarcodes' => 'OfflineBarcodes',
        'preAllocatedTrackingNumber' => 'PreAllocatedTrackingNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'serviceLevel' => 'setServiceLevel',
        'ebayVtn' => 'setEbayVtn',
        'serviceEnhancements' => 'setServiceEnhancements',
        'offlineBarcode' => 'setOfflineBarcode',
        'offlineBarcodes' => 'setOfflineBarcodes',
        'preAllocatedTrackingNumber' => 'setPreAllocatedTrackingNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'serviceLevel' => 'getServiceLevel',
        'ebayVtn' => 'getEbayVtn',
        'serviceEnhancements' => 'getServiceEnhancements',
        'offlineBarcode' => 'getOfflineBarcode',
        'offlineBarcodes' => 'getOfflineBarcodes',
        'preAllocatedTrackingNumber' => 'getPreAllocatedTrackingNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['serviceLevel'] = isset($data['serviceLevel']) ? $data['serviceLevel'] : null;
        $this->container['ebayVtn'] = isset($data['ebayVtn']) ? $data['ebayVtn'] : null;
        $this->container['serviceEnhancements'] = isset($data['serviceEnhancements']) ? $data['serviceEnhancements'] : null;
        $this->container['offlineBarcode'] = isset($data['offlineBarcode']) ? $data['offlineBarcode'] : null;
        $this->container['offlineBarcodes'] = isset($data['offlineBarcodes']) ? $data['offlineBarcodes'] : null;
        $this->container['preAllocatedTrackingNumber'] = isset($data['preAllocatedTrackingNumber']) ? $data['preAllocatedTrackingNumber'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets serviceLevel
     *
     * @return string
     */
    public function getServiceLevel()
    {
        return $this->container['serviceLevel'];
    }

    /**
     * Sets serviceLevel
     *
     * @param string $serviceLevel The Royal Mail service level of the service specified in the ServiceCode field.  <br />Valid values are 01-99. <br />Defaults to lowest service level available for the specified service if not provided.
     *
     * @return $this
     */
    public function setServiceLevel($serviceLevel)
    {
        $this->container['serviceLevel'] = $serviceLevel;

        return $this;
    }

    /**
     * Gets ebayVtn
     *
     * @return string
     */
    public function getEbayVtn()
    {
        return $this->container['ebayVtn'];
    }

    /**
     * Sets ebayVtn
     *
     * @param string $ebayVtn The eBay Virtual Tracking Number. This should be provided for all shipments that relate to orders created on eBay, so that the shipment tracking data can be made available on eBay.
     *
     * @return $this
     */
    public function setEbayVtn($ebayVtn)
    {
        $this->container['ebayVtn'] = $ebayVtn;

        return $this;
    }

    /**
     * Gets serviceEnhancements
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailServiceEnhancement[]
     */
    public function getServiceEnhancements()
    {
        return $this->container['serviceEnhancements'];
    }

    /**
     * Sets serviceEnhancements
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailServiceEnhancement[] $serviceEnhancements Service Enhancements <br />Any enhancements that you would like to add to the requested service. <br />A maximum of 4 service enhancements can be used per shipment.
     *
     * @return $this
     */
    public function setServiceEnhancements($serviceEnhancements)
    {
        $this->container['serviceEnhancements'] = $serviceEnhancements;

        return $this;
    }

    /**
     * Gets offlineBarcode
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcode
     */
    public function getOfflineBarcode()
    {
        return $this->container['offlineBarcode'];
    }

    /**
     * Sets offlineBarcode
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcode $offlineBarcode offlineBarcode
     *
     * @return $this
     */
    public function setOfflineBarcode($offlineBarcode)
    {
        $this->container['offlineBarcode'] = $offlineBarcode;

        return $this;
    }

    /**
     * Gets offlineBarcodes
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcode[]
     */
    public function getOfflineBarcodes()
    {
        return $this->container['offlineBarcodes'];
    }

    /**
     * Sets offlineBarcodes
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcode[] $offlineBarcodes The Offline Barcodes element is to create shipment records for shipments that had a tracking number allocated outside of PRO SHIPPING.  <br />Offline Barcoding is only available if it has been activated on your customer account in the GUI.  <br />If Offline Barcodes information is provided, then Process is the only valid action accepted in the Action field.
     *
     * @return $this
     */
    public function setOfflineBarcodes($offlineBarcodes)
    {
        $this->container['offlineBarcodes'] = $offlineBarcodes;

        return $this;
    }

    /**
     * Gets preAllocatedTrackingNumber
     *
     * @return string
     */
    public function getPreAllocatedTrackingNumber()
    {
        return $this->container['preAllocatedTrackingNumber'];
    }

    /**
     * Sets preAllocatedTrackingNumber
     *
     * @param string $preAllocatedTrackingNumber The pre-allocated tracking number to use for the shipment. Shipping Account, Shipping Location, Service Code, Destination Country and Postcode where required for the Country of Destination must match the one sent when the pre-allocation barcode was requested.
     *
     * @return $this
     */
    public function setPreAllocatedTrackingNumber($preAllocatedTrackingNumber)
    {
        $this->container['preAllocatedTrackingNumber'] = $preAllocatedTrackingNumber;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
