<?php
/**
 * RoyalMailGetOfflineBarcodingRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailGetOfflineBarcodingRequest Class Doc Comment
 *
 * @category Class
 * @description Royal Mail Get Offline Barcoding Request
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailGetOfflineBarcodingRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailGetOfflineBarcodingRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shippingLocationId' => 'string',
        'shippingAccountId' => 'string',
        'serviceCode' => 'string',
        'serviceLevel' => 'string',
        'serviceEnhancementCode' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcodingEnhancementCode',
        'channelId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shippingLocationId' => null,
        'shippingAccountId' => null,
        'serviceCode' => null,
        'serviceLevel' => null,
        'serviceEnhancementCode' => null,
        'channelId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shippingLocationId' => 'ShippingLocationId',
        'shippingAccountId' => 'ShippingAccountId',
        'serviceCode' => 'ServiceCode',
        'serviceLevel' => 'ServiceLevel',
        'serviceEnhancementCode' => 'ServiceEnhancementCode',
        'channelId' => 'ChannelId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shippingLocationId' => 'setShippingLocationId',
        'shippingAccountId' => 'setShippingAccountId',
        'serviceCode' => 'setServiceCode',
        'serviceLevel' => 'setServiceLevel',
        'serviceEnhancementCode' => 'setServiceEnhancementCode',
        'channelId' => 'setChannelId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shippingLocationId' => 'getShippingLocationId',
        'shippingAccountId' => 'getShippingAccountId',
        'serviceCode' => 'getServiceCode',
        'serviceLevel' => 'getServiceLevel',
        'serviceEnhancementCode' => 'getServiceEnhancementCode',
        'channelId' => 'getChannelId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shippingLocationId'] = isset($data['shippingLocationId']) ? $data['shippingLocationId'] : null;
        $this->container['shippingAccountId'] = isset($data['shippingAccountId']) ? $data['shippingAccountId'] : null;
        $this->container['serviceCode'] = isset($data['serviceCode']) ? $data['serviceCode'] : null;
        $this->container['serviceLevel'] = isset($data['serviceLevel']) ? $data['serviceLevel'] : null;
        $this->container['serviceEnhancementCode'] = isset($data['serviceEnhancementCode']) ? $data['serviceEnhancementCode'] : null;
        $this->container['channelId'] = isset($data['channelId']) ? $data['channelId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shippingAccountId'] === null) {
            $invalidProperties[] = "'shippingAccountId' can't be null";
        }
        if ($this->container['serviceCode'] === null) {
            $invalidProperties[] = "'serviceCode' can't be null";
        }
        if ($this->container['serviceLevel'] === null) {
            $invalidProperties[] = "'serviceLevel' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shippingLocationId
     *
     * @return string
     */
    public function getShippingLocationId()
    {
        return $this->container['shippingLocationId'];
    }

    /**
     * Sets shippingLocationId
     *
     * @param string $shippingLocationId This can be populated with either the Shipping Location ID assigned by PRO SHIPPING or the Shipping Location Alias set when the Shipping Location was created. Optional if the shipping account only has one Shipping Location assigned. If the Shipping Account has multiple Shipping Locations, then this field must be populated.
     *
     * @return $this
     */
    public function setShippingLocationId($shippingLocationId)
    {
        $this->container['shippingLocationId'] = $shippingLocationId;

        return $this;
    }

    /**
     * Gets shippingAccountId
     *
     * @return string
     */
    public function getShippingAccountId()
    {
        return $this->container['shippingAccountId'];
    }

    /**
     * Sets shippingAccountId
     *
     * @param string $shippingAccountId Shipping Account the number range is being requested for. This can be populated with either the Shipping Account ID assigned by PRO SHIPPING or the Shipping Account Alias set when the Shipping Account was created.
     *
     * @return $this
     */
    public function setShippingAccountId($shippingAccountId)
    {
        $this->container['shippingAccountId'] = $shippingAccountId;

        return $this;
    }

    /**
     * Gets serviceCode
     *
     * @return string
     */
    public function getServiceCode()
    {
        return $this->container['serviceCode'];
    }

    /**
     * Sets serviceCode
     *
     * @param string $serviceCode Service Code
     *
     * @return $this
     */
    public function setServiceCode($serviceCode)
    {
        $this->container['serviceCode'] = $serviceCode;

        return $this;
    }

    /**
     * Gets serviceLevel
     *
     * @return string
     */
    public function getServiceLevel()
    {
        return $this->container['serviceLevel'];
    }

    /**
     * Sets serviceLevel
     *
     * @param string $serviceLevel The Royal Mail service level of the service specified in the ServiceCode field. <br />Valid values are 01-99.
     *
     * @return $this
     */
    public function setServiceLevel($serviceLevel)
    {
        $this->container['serviceLevel'] = $serviceLevel;

        return $this;
    }

    /**
     * Gets serviceEnhancementCode
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcodingEnhancementCode
     */
    public function getServiceEnhancementCode()
    {
        return $this->container['serviceEnhancementCode'];
    }

    /**
     * Sets serviceEnhancementCode
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailOfflineBarcodingEnhancementCode $serviceEnhancementCode serviceEnhancementCode
     *
     * @return $this
     */
    public function setServiceEnhancementCode($serviceEnhancementCode)
    {
        $this->container['serviceEnhancementCode'] = $serviceEnhancementCode;

        return $this;
    }

    /**
     * Gets channelId
     *
     * @return string
     */
    public function getChannelId()
    {
        return $this->container['channelId'];
    }

    /**
     * Sets channelId
     *
     * @param string $channelId The Channel ID agreed with Royal Mail for the offline barcodes. If no value is sent in the request then the Channel ID assigned in PRO SHIPPING will be used.
     *
     * @return $this
     */
    public function setChannelId($channelId)
    {
        $this->container['channelId'] = $channelId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
