<?php
/**
 * RoyalMailShipmentResponseCarrierSpecificsPackageResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailShipmentResponseCarrierSpecificsPackageResponse Class Doc Comment
 *
 * @category Class
 * @description Package Response
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailShipmentResponseCarrierSpecificsPackageResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailShipmentResponseCarrierSpecificsPackageResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'packageOccurrence' => 'int',
        'trackingNumber' => 'string',
        'carrierTrackingUrl' => 'string',
        'carrierDetails' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentResponseCarrierSpecifics',
        'shipmentId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'packageOccurrence' => 'int32',
        'trackingNumber' => null,
        'carrierTrackingUrl' => 'uri',
        'carrierDetails' => null,
        'shipmentId' => 'uuid'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'packageOccurrence' => 'PackageOccurrence',
        'trackingNumber' => 'TrackingNumber',
        'carrierTrackingUrl' => 'CarrierTrackingUrl',
        'carrierDetails' => 'CarrierDetails',
        'shipmentId' => 'ShipmentId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'packageOccurrence' => 'setPackageOccurrence',
        'trackingNumber' => 'setTrackingNumber',
        'carrierTrackingUrl' => 'setCarrierTrackingUrl',
        'carrierDetails' => 'setCarrierDetails',
        'shipmentId' => 'setShipmentId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'packageOccurrence' => 'getPackageOccurrence',
        'trackingNumber' => 'getTrackingNumber',
        'carrierTrackingUrl' => 'getCarrierTrackingUrl',
        'carrierDetails' => 'getCarrierDetails',
        'shipmentId' => 'getShipmentId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['packageOccurrence'] = isset($data['packageOccurrence']) ? $data['packageOccurrence'] : null;
        $this->container['trackingNumber'] = isset($data['trackingNumber']) ? $data['trackingNumber'] : null;
        $this->container['carrierTrackingUrl'] = isset($data['carrierTrackingUrl']) ? $data['carrierTrackingUrl'] : null;
        $this->container['carrierDetails'] = isset($data['carrierDetails']) ? $data['carrierDetails'] : null;
        $this->container['shipmentId'] = isset($data['shipmentId']) ? $data['shipmentId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets packageOccurrence
     *
     * @return int
     */
    public function getPackageOccurrence()
    {
        return $this->container['packageOccurrence'];
    }

    /**
     * Sets packageOccurrence
     *
     * @param int $packageOccurrence Package Occurrence <br />The package occurrence you gave to the package, or if not provided, the default package occurrence.
     *
     * @return $this
     */
    public function setPackageOccurrence($packageOccurrence)
    {
        $this->container['packageOccurrence'] = $packageOccurrence;

        return $this;
    }

    /**
     * Gets trackingNumber
     *
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->container['trackingNumber'];
    }

    /**
     * Sets trackingNumber
     *
     * @param string $trackingNumber Tracking Number <br />The tracking number for this package occurrence.
     *
     * @return $this
     */
    public function setTrackingNumber($trackingNumber)
    {
        $this->container['trackingNumber'] = $trackingNumber;

        return $this;
    }

    /**
     * Gets carrierTrackingUrl
     *
     * @return string
     */
    public function getCarrierTrackingUrl()
    {
        return $this->container['carrierTrackingUrl'];
    }

    /**
     * Sets carrierTrackingUrl
     *
     * @param string $carrierTrackingUrl Tracking URL <br />The carrier's tracking URL. <br />Only present if available.
     *
     * @return $this
     */
    public function setCarrierTrackingUrl($carrierTrackingUrl)
    {
        $this->container['carrierTrackingUrl'] = $carrierTrackingUrl;

        return $this;
    }

    /**
     * Gets carrierDetails
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentResponseCarrierSpecifics
     */
    public function getCarrierDetails()
    {
        return $this->container['carrierDetails'];
    }

    /**
     * Sets carrierDetails
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentResponseCarrierSpecifics $carrierDetails carrierDetails
     *
     * @return $this
     */
    public function setCarrierDetails($carrierDetails)
    {
        $this->container['carrierDetails'] = $carrierDetails;

        return $this;
    }

    /**
     * Gets shipmentId
     *
     * @return string
     */
    public function getShipmentId()
    {
        return $this->container['shipmentId'];
    }

    /**
     * Sets shipmentId
     *
     * @param string $shipmentId Shipment Id <br />Only populated if the service is a non-consignment service.
     *
     * @return $this
     */
    public function setShipmentId($shipmentId)
    {
        $this->container['shipmentId'] = $shipmentId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
