<?php
/**
 * RoyalMailAddShippingAccountLocation
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailAddShippingAccountLocation Class Doc Comment
 *
 * @category Class
 * @description Royal Mail Add Shipping Account Location
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailAddShippingAccountLocation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailAddShippingAccountLocation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shippingLocationId' => 'string',
        'shippingLocation' => '\RoyalMailV4\ShipmentsApi\Model\AddShippingAccountLocationNewLocation',
        'postingLocationCode' => 'string',
        'obaAccessCode' => 'string',
        'receivingHubCode' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shippingLocationId' => null,
        'shippingLocation' => null,
        'postingLocationCode' => null,
        'obaAccessCode' => null,
        'receivingHubCode' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shippingLocationId' => 'ShippingLocationId',
        'shippingLocation' => 'ShippingLocation',
        'postingLocationCode' => 'PostingLocationCode',
        'obaAccessCode' => 'ObaAccessCode',
        'receivingHubCode' => 'ReceivingHubCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shippingLocationId' => 'setShippingLocationId',
        'shippingLocation' => 'setShippingLocation',
        'postingLocationCode' => 'setPostingLocationCode',
        'obaAccessCode' => 'setObaAccessCode',
        'receivingHubCode' => 'setReceivingHubCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shippingLocationId' => 'getShippingLocationId',
        'shippingLocation' => 'getShippingLocation',
        'postingLocationCode' => 'getPostingLocationCode',
        'obaAccessCode' => 'getObaAccessCode',
        'receivingHubCode' => 'getReceivingHubCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shippingLocationId'] = isset($data['shippingLocationId']) ? $data['shippingLocationId'] : null;
        $this->container['shippingLocation'] = isset($data['shippingLocation']) ? $data['shippingLocation'] : null;
        $this->container['postingLocationCode'] = isset($data['postingLocationCode']) ? $data['postingLocationCode'] : null;
        $this->container['obaAccessCode'] = isset($data['obaAccessCode']) ? $data['obaAccessCode'] : null;
        $this->container['receivingHubCode'] = isset($data['receivingHubCode']) ? $data['receivingHubCode'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['postingLocationCode'] === null) {
            $invalidProperties[] = "'postingLocationCode' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shippingLocationId
     *
     * @return string
     */
    public function getShippingLocationId()
    {
        return $this->container['shippingLocationId'];
    }

    /**
     * Sets shippingLocationId
     *
     * @param string $shippingLocationId Shipping Location Identifier <br />PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). <br /> <br />Link an existing location to this account. <br />Either a Shipping Location Id must be provided, or the details of a new shipping location provided.
     *
     * @return $this
     */
    public function setShippingLocationId($shippingLocationId)
    {
        $this->container['shippingLocationId'] = $shippingLocationId;

        return $this;
    }

    /**
     * Gets shippingLocation
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\AddShippingAccountLocationNewLocation
     */
    public function getShippingLocation()
    {
        return $this->container['shippingLocation'];
    }

    /**
     * Sets shippingLocation
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\AddShippingAccountLocationNewLocation $shippingLocation shippingLocation
     *
     * @return $this
     */
    public function setShippingLocation($shippingLocation)
    {
        $this->container['shippingLocation'] = $shippingLocation;

        return $this;
    }

    /**
     * Gets postingLocationCode
     *
     * @return string
     */
    public function getPostingLocationCode()
    {
        return $this->container['postingLocationCode'];
    }

    /**
     * Sets postingLocationCode
     *
     * @param string $postingLocationCode Posting Location Code <br />The number assigned to this Location by Royal Mail.
     *
     * @return $this
     */
    public function setPostingLocationCode($postingLocationCode)
    {
        $this->container['postingLocationCode'] = $postingLocationCode;

        return $this;
    }

    /**
     * Gets obaAccessCode
     *
     * @return string
     */
    public function getObaAccessCode()
    {
        return $this->container['obaAccessCode'];
    }

    /**
     * Sets obaAccessCode
     *
     * @param string $obaAccessCode OBA Access Code <br />A password for the account to access the OBA services. <br />A Royal Mail shipping account cannot be active unless the OBA Access code has been provided.
     *
     * @return $this
     */
    public function setObaAccessCode($obaAccessCode)
    {
        $this->container['obaAccessCode'] = $obaAccessCode;

        return $this;
    }

    /**
     * Gets receivingHubCode
     *
     * @return string
     */
    public function getReceivingHubCode()
    {
        return $this->container['receivingHubCode'];
    }

    /**
     * Sets receivingHubCode
     *
     * @param string $receivingHubCode Receiving Hub Code <br />Receiving Hub/Regional Distribution Center used for this Shipping Location. <br />Must be an existing receiving hub code. <br />Please refer to Royal Mail ReceivingHubs for a list of possible receiving hubs. <br />If the receiving hub is not provided, we will match it to the one that corresponds to the postcode of the location's address.
     *
     * @return $this
     */
    public function setReceivingHubCode($receivingHubCode)
    {
        $this->container['receivingHubCode'] = $receivingHubCode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
