<?php
/**
 * RoyalMailAddShippingAccountRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailAddShippingAccountRequest Class Doc Comment
 *
 * @category Class
 * @description Royal Mail Add Shipping Account Request
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailAddShippingAccountRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailAddShippingAccountRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accountNumber' => 'string',
        'accountType' => '\RoyalMailV4\ShipmentsApi\Model\AccountType',
        'accountName' => 'string',
        'accountRegisteredEmail' => 'string',
        'accountAlias' => 'string',
        'contactName' => 'string',
        'contactNumber' => 'string',
        'shippingLocations' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailAddShippingAccountLocation[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accountNumber' => null,
        'accountType' => null,
        'accountName' => null,
        'accountRegisteredEmail' => 'email',
        'accountAlias' => null,
        'contactName' => null,
        'contactNumber' => 'tel',
        'shippingLocations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accountNumber' => 'AccountNumber',
        'accountType' => 'AccountType',
        'accountName' => 'AccountName',
        'accountRegisteredEmail' => 'AccountRegisteredEmail',
        'accountAlias' => 'AccountAlias',
        'contactName' => 'ContactName',
        'contactNumber' => 'ContactNumber',
        'shippingLocations' => 'ShippingLocations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accountNumber' => 'setAccountNumber',
        'accountType' => 'setAccountType',
        'accountName' => 'setAccountName',
        'accountRegisteredEmail' => 'setAccountRegisteredEmail',
        'accountAlias' => 'setAccountAlias',
        'contactName' => 'setContactName',
        'contactNumber' => 'setContactNumber',
        'shippingLocations' => 'setShippingLocations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accountNumber' => 'getAccountNumber',
        'accountType' => 'getAccountType',
        'accountName' => 'getAccountName',
        'accountRegisteredEmail' => 'getAccountRegisteredEmail',
        'accountAlias' => 'getAccountAlias',
        'contactName' => 'getContactName',
        'contactNumber' => 'getContactNumber',
        'shippingLocations' => 'getShippingLocations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accountNumber'] = isset($data['accountNumber']) ? $data['accountNumber'] : null;
        $this->container['accountType'] = isset($data['accountType']) ? $data['accountType'] : null;
        $this->container['accountName'] = isset($data['accountName']) ? $data['accountName'] : null;
        $this->container['accountRegisteredEmail'] = isset($data['accountRegisteredEmail']) ? $data['accountRegisteredEmail'] : null;
        $this->container['accountAlias'] = isset($data['accountAlias']) ? $data['accountAlias'] : null;
        $this->container['contactName'] = isset($data['contactName']) ? $data['contactName'] : null;
        $this->container['contactNumber'] = isset($data['contactNumber']) ? $data['contactNumber'] : null;
        $this->container['shippingLocations'] = isset($data['shippingLocations']) ? $data['shippingLocations'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['accountNumber'] === null) {
            $invalidProperties[] = "'accountNumber' can't be null";
        }
        if ($this->container['accountType'] === null) {
            $invalidProperties[] = "'accountType' can't be null";
        }
        if ($this->container['accountRegisteredEmail'] === null) {
            $invalidProperties[] = "'accountRegisteredEmail' can't be null";
        }
        if ($this->container['accountAlias'] === null) {
            $invalidProperties[] = "'accountAlias' can't be null";
        }
        if ($this->container['contactName'] === null) {
            $invalidProperties[] = "'contactName' can't be null";
        }
        if ($this->container['contactNumber'] === null) {
            $invalidProperties[] = "'contactNumber' can't be null";
        }
        if ($this->container['shippingLocations'] === null) {
            $invalidProperties[] = "'shippingLocations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accountNumber
     *
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->container['accountNumber'];
    }

    /**
     * Sets accountNumber
     *
     * @param string $accountNumber Carrier Account Number <br />The account number given by the carrier.
     *
     * @return $this
     */
    public function setAccountNumber($accountNumber)
    {
        $this->container['accountNumber'] = $accountNumber;

        return $this;
    }

    /**
     * Gets accountType
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\AccountType
     */
    public function getAccountType()
    {
        return $this->container['accountType'];
    }

    /**
     * Sets accountType
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\AccountType $accountType accountType
     *
     * @return $this
     */
    public function setAccountType($accountType)
    {
        $this->container['accountType'] = $accountType;

        return $this;
    }

    /**
     * Gets accountName
     *
     * @return string
     */
    public function getAccountName()
    {
        return $this->container['accountName'];
    }

    /**
     * Sets accountName
     *
     * @param string $accountName Account Name <br />The name on this Account. <br />Defaults to your Customer name if not provided.
     *
     * @return $this
     */
    public function setAccountName($accountName)
    {
        $this->container['accountName'] = $accountName;

        return $this;
    }

    /**
     * Gets accountRegisteredEmail
     *
     * @return string
     */
    public function getAccountRegisteredEmail()
    {
        return $this->container['accountRegisteredEmail'];
    }

    /**
     * Sets accountRegisteredEmail
     *
     * @param string $accountRegisteredEmail Account Registered Email <br />This is the email that was used to register your Shipping Account with the carrier when the Shipping Account was created.
     *
     * @return $this
     */
    public function setAccountRegisteredEmail($accountRegisteredEmail)
    {
        $this->container['accountRegisteredEmail'] = $accountRegisteredEmail;

        return $this;
    }

    /**
     * Gets accountAlias
     *
     * @return string
     */
    public function getAccountAlias()
    {
        return $this->container['accountAlias'];
    }

    /**
     * Sets accountAlias
     *
     * @param string $accountAlias Account Alias <br />Your identifier for this account. Must be unique.
     *
     * @return $this
     */
    public function setAccountAlias($accountAlias)
    {
        $this->container['accountAlias'] = $accountAlias;

        return $this;
    }

    /**
     * Gets contactName
     *
     * @return string
     */
    public function getContactName()
    {
        return $this->container['contactName'];
    }

    /**
     * Sets contactName
     *
     * @param string $contactName Contact Name <br />Used in a create shipment request as the shipper's contact name if the shipper address is not provided.
     *
     * @return $this
     */
    public function setContactName($contactName)
    {
        $this->container['contactName'] = $contactName;

        return $this;
    }

    /**
     * Gets contactNumber
     *
     * @return string
     */
    public function getContactNumber()
    {
        return $this->container['contactNumber'];
    }

    /**
     * Sets contactNumber
     *
     * @param string $contactNumber Contact Number <br />Used in a create shipment request as the shipper's contact number if the shipper address is not provided, and the contact number is not set on the associated shipping location.
     *
     * @return $this
     */
    public function setContactNumber($contactNumber)
    {
        $this->container['contactNumber'] = $contactNumber;

        return $this;
    }

    /**
     * Gets shippingLocations
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailAddShippingAccountLocation[]
     */
    public function getShippingLocations()
    {
        return $this->container['shippingLocations'];
    }

    /**
     * Sets shippingLocations
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailAddShippingAccountLocation[] $shippingLocations Shipping Locations <br />At least one location is required when adding a shipping account. <br />If providing a new location when adding the account, only one location can be added.
     *
     * @return $this
     */
    public function setShippingLocations($shippingLocations)
    {
        $this->container['shippingLocations'] = $shippingLocations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
