<?php
/**
 * RoyalMailShipmentRequestCarrierSpecificsRoyalMailPackageRoyalMailLabelFormatCreateShipmentRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailShipmentRequestCarrierSpecificsRoyalMailPackageRoyalMailLabelFormatCreateShipmentRequest Class Doc Comment
 *
 * @category Class
 * @description Create Shipment Request
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailShipmentRequestCarrierSpecificsRoyalMailPackageRoyalMailLabelFormatCreateShipmentRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailShipmentRequestCarrierSpecificsRoyalMailPackageRoyalMailLabelFormatCreateShipmentRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shipmentInformation' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormatShipmentInformation',
        'shipper' => '\RoyalMailV4\ShipmentsApi\Model\Shipper',
        'destination' => '\RoyalMailV4\ShipmentsApi\Model\Destination',
        'carrierSpecifics' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentRequestCarrierSpecifics',
        'packages' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailPackage[]',
        'items' => '\RoyalMailV4\ShipmentsApi\Model\Item[]',
        'customs' => '\RoyalMailV4\ShipmentsApi\Model\Customs',
        'returnToSender' => '\RoyalMailV4\ShipmentsApi\Model\ReturnToSender'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shipmentInformation' => null,
        'shipper' => null,
        'destination' => null,
        'carrierSpecifics' => null,
        'packages' => null,
        'items' => null,
        'customs' => null,
        'returnToSender' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shipmentInformation' => 'ShipmentInformation',
        'shipper' => 'Shipper',
        'destination' => 'Destination',
        'carrierSpecifics' => 'CarrierSpecifics',
        'packages' => 'Packages',
        'items' => 'Items',
        'customs' => 'Customs',
        'returnToSender' => 'ReturnToSender'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shipmentInformation' => 'setShipmentInformation',
        'shipper' => 'setShipper',
        'destination' => 'setDestination',
        'carrierSpecifics' => 'setCarrierSpecifics',
        'packages' => 'setPackages',
        'items' => 'setItems',
        'customs' => 'setCustoms',
        'returnToSender' => 'setReturnToSender'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shipmentInformation' => 'getShipmentInformation',
        'shipper' => 'getShipper',
        'destination' => 'getDestination',
        'carrierSpecifics' => 'getCarrierSpecifics',
        'packages' => 'getPackages',
        'items' => 'getItems',
        'customs' => 'getCustoms',
        'returnToSender' => 'getReturnToSender'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipmentInformation'] = isset($data['shipmentInformation']) ? $data['shipmentInformation'] : null;
        $this->container['shipper'] = isset($data['shipper']) ? $data['shipper'] : null;
        $this->container['destination'] = isset($data['destination']) ? $data['destination'] : null;
        $this->container['carrierSpecifics'] = isset($data['carrierSpecifics']) ? $data['carrierSpecifics'] : null;
        $this->container['packages'] = isset($data['packages']) ? $data['packages'] : null;
        $this->container['items'] = isset($data['items']) ? $data['items'] : null;
        $this->container['customs'] = isset($data['customs']) ? $data['customs'] : null;
        $this->container['returnToSender'] = isset($data['returnToSender']) ? $data['returnToSender'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shipmentInformation'] === null) {
            $invalidProperties[] = "'shipmentInformation' can't be null";
        }
        if ($this->container['shipper'] === null) {
            $invalidProperties[] = "'shipper' can't be null";
        }
        if ($this->container['destination'] === null) {
            $invalidProperties[] = "'destination' can't be null";
        }
        if ($this->container['packages'] === null) {
            $invalidProperties[] = "'packages' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipmentInformation
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormatShipmentInformation
     */
    public function getShipmentInformation()
    {
        return $this->container['shipmentInformation'];
    }

    /**
     * Sets shipmentInformation
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormatShipmentInformation $shipmentInformation shipmentInformation
     *
     * @return $this
     */
    public function setShipmentInformation($shipmentInformation)
    {
        $this->container['shipmentInformation'] = $shipmentInformation;

        return $this;
    }

    /**
     * Gets shipper
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\Shipper
     */
    public function getShipper()
    {
        return $this->container['shipper'];
    }

    /**
     * Sets shipper
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\Shipper $shipper shipper
     *
     * @return $this
     */
    public function setShipper($shipper)
    {
        $this->container['shipper'] = $shipper;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\Destination
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\Destination $destination destination
     *
     * @return $this
     */
    public function setDestination($destination)
    {
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets carrierSpecifics
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentRequestCarrierSpecifics
     */
    public function getCarrierSpecifics()
    {
        return $this->container['carrierSpecifics'];
    }

    /**
     * Sets carrierSpecifics
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentRequestCarrierSpecifics $carrierSpecifics carrierSpecifics
     *
     * @return $this
     */
    public function setCarrierSpecifics($carrierSpecifics)
    {
        $this->container['carrierSpecifics'] = $carrierSpecifics;

        return $this;
    }

    /**
     * Gets packages
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailPackage[]
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailPackage[] $packages Shipment Packages <br />The packages that are being sent in this shipment. <br />There must be at least 1 package. <br />A maximum of 99 packages is allowed.
     *
     * @return $this
     */
    public function setPackages($packages)
    {
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\Item[]
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\Item[] $items Shipment Items <br />The items contained in the shipment, i.e. the goods/products being shipped  <br />Item information is required for dutiable shipments for customs purposes. <br />Non-Dutiable shipments and 'Documents Only' (DOX) shipments do not require item information. <br />If Item Verification check on shipment creation is enabled, the maximum number of distinct items that will be verified in one shipment is 15.
     *
     * @return $this
     */
    public function setItems($items)
    {
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets customs
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\Customs
     */
    public function getCustoms()
    {
        return $this->container['customs'];
    }

    /**
     * Sets customs
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\Customs $customs customs
     *
     * @return $this
     */
    public function setCustoms($customs)
    {
        $this->container['customs'] = $customs;

        return $this;
    }

    /**
     * Gets returnToSender
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\ReturnToSender
     */
    public function getReturnToSender()
    {
        return $this->container['returnToSender'];
    }

    /**
     * Sets returnToSender
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\ReturnToSender $returnToSender returnToSender
     *
     * @return $this
     */
    public function setReturnToSender($returnToSender)
    {
        $this->container['returnToSender'] = $returnToSender;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
