<?php
/**
 * RoyalMailPackage
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailPackage Class Doc Comment
 *
 * @category Class
 * @description Royal Mail Package
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailPackage implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailPackage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'packageOccurrence' => 'int',
        'packageType' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailPackageTypeCode',
        'declaredWeight' => 'double',
        'declaredValue' => 'double',
        'dimensions' => '\RoyalMailV4\ShipmentsApi\Model\Dimensions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'packageOccurrence' => 'int32',
        'packageType' => null,
        'declaredWeight' => 'double',
        'declaredValue' => 'double',
        'dimensions' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'packageOccurrence' => 'PackageOccurrence',
        'packageType' => 'PackageType',
        'declaredWeight' => 'DeclaredWeight',
        'declaredValue' => 'DeclaredValue',
        'dimensions' => 'Dimensions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'packageOccurrence' => 'setPackageOccurrence',
        'packageType' => 'setPackageType',
        'declaredWeight' => 'setDeclaredWeight',
        'declaredValue' => 'setDeclaredValue',
        'dimensions' => 'setDimensions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'packageOccurrence' => 'getPackageOccurrence',
        'packageType' => 'getPackageType',
        'declaredWeight' => 'getDeclaredWeight',
        'declaredValue' => 'getDeclaredValue',
        'dimensions' => 'getDimensions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['packageOccurrence'] = isset($data['packageOccurrence']) ? $data['packageOccurrence'] : null;
        $this->container['packageType'] = isset($data['packageType']) ? $data['packageType'] : null;
        $this->container['declaredWeight'] = isset($data['declaredWeight']) ? $data['declaredWeight'] : null;
        $this->container['declaredValue'] = isset($data['declaredValue']) ? $data['declaredValue'] : null;
        $this->container['dimensions'] = isset($data['dimensions']) ? $data['dimensions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets packageOccurrence
     *
     * @return int
     */
    public function getPackageOccurrence()
    {
        return $this->container['packageOccurrence'];
    }

    /**
     * Sets packageOccurrence
     *
     * @param int $packageOccurrence Used to match a returned Package ID to this package. <br />Can also be used to assign items to this package. <br />If provided, each package occurrence must be unique. <br />Note: For dutiable multi-package shipments that are not using a consignment service, items must be assigned to a package so that accurate customs information is given. <br />Therefore, if the shipment contains more than one package, and it isn't using a consignment service, then Package Occurrence is required.
     *
     * @return $this
     */
    public function setPackageOccurrence($packageOccurrence)
    {
        $this->container['packageOccurrence'] = $packageOccurrence;

        return $this;
    }

    /**
     * Gets packageType
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailPackageTypeCode
     */
    public function getPackageType()
    {
        return $this->container['packageType'];
    }

    /**
     * Sets packageType
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailPackageTypeCode $packageType packageType
     *
     * @return $this
     */
    public function setPackageType($packageType)
    {
        $this->container['packageType'] = $packageType;

        return $this;
    }

    /**
     * Gets declaredWeight
     *
     * @return double
     */
    public function getDeclaredWeight()
    {
        return $this->container['declaredWeight'];
    }

    /**
     * Sets declaredWeight
     *
     * @param double $declaredWeight The total weight of this package in the unit of measure specified by WeightUnitOfMeasure (defaults to KG). <br />The minimum weight allowed is 1 gram. <br />The maximum weight is dependent on the carrier / service / destination. <br />Mandatory for shipments using non-consignment services.
     *
     * @return $this
     */
    public function setDeclaredWeight($declaredWeight)
    {
        $this->container['declaredWeight'] = $declaredWeight;

        return $this;
    }

    /**
     * Gets declaredValue
     *
     * @return double
     */
    public function getDeclaredValue()
    {
        return $this->container['declaredValue'];
    }

    /**
     * Sets declaredValue
     *
     * @param double $declaredValue The declared value of the total package in the currency specified. <br />If provided, the value must be equal or greater than the sum of all item values assigned to this package. <br />If not provided it defaults to the sum of all item values. <br />Used for shipment using non-consignment services, but not mandatory.
     *
     * @return $this
     */
    public function setDeclaredValue($declaredValue)
    {
        $this->container['declaredValue'] = $declaredValue;

        return $this;
    }

    /**
     * Gets dimensions
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\Dimensions
     */
    public function getDimensions()
    {
        return $this->container['dimensions'];
    }

    /**
     * Sets dimensions
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\Dimensions $dimensions dimensions
     *
     * @return $this
     */
    public function setDimensions($dimensions)
    {
        $this->container['dimensions'] = $dimensions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
