<?php
/**
 * RoyalMailLabelFormatRoyalMailShipmentResponseCarrierSpecificsPackageResponseCreateShipmentResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailLabelFormatRoyalMailShipmentResponseCarrierSpecificsPackageResponseCreateShipmentResponse Class Doc Comment
 *
 * @category Class
 * @description Create Shipment Response
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailLabelFormatRoyalMailShipmentResponseCarrierSpecificsPackageResponseCreateShipmentResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailLabelFormatRoyalMailShipmentResponseCarrierSpecificsPackageResponseCreateShipmentResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'consignmentShipmentId' => 'string',
        'consignmentTrackingNumber' => 'string',
        'consignmentCarrierTrackingUrl' => 'string',
        'labels' => 'string',
        'labelFormat' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormat',
        'packages' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentResponseCarrierSpecificsPackageResponse[]',
        'documents' => 'string',
        'documentFormat' => '\RoyalMailV4\ShipmentsApi\Model\DocumentFormat'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'consignmentShipmentId' => 'uuid',
        'consignmentTrackingNumber' => null,
        'consignmentCarrierTrackingUrl' => 'uri',
        'labels' => null,
        'labelFormat' => null,
        'packages' => null,
        'documents' => null,
        'documentFormat' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'consignmentShipmentId' => 'ConsignmentShipmentId',
        'consignmentTrackingNumber' => 'ConsignmentTrackingNumber',
        'consignmentCarrierTrackingUrl' => 'ConsignmentCarrierTrackingUrl',
        'labels' => 'Labels',
        'labelFormat' => 'LabelFormat',
        'packages' => 'Packages',
        'documents' => 'Documents',
        'documentFormat' => 'DocumentFormat'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'consignmentShipmentId' => 'setConsignmentShipmentId',
        'consignmentTrackingNumber' => 'setConsignmentTrackingNumber',
        'consignmentCarrierTrackingUrl' => 'setConsignmentCarrierTrackingUrl',
        'labels' => 'setLabels',
        'labelFormat' => 'setLabelFormat',
        'packages' => 'setPackages',
        'documents' => 'setDocuments',
        'documentFormat' => 'setDocumentFormat'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'consignmentShipmentId' => 'getConsignmentShipmentId',
        'consignmentTrackingNumber' => 'getConsignmentTrackingNumber',
        'consignmentCarrierTrackingUrl' => 'getConsignmentCarrierTrackingUrl',
        'labels' => 'getLabels',
        'labelFormat' => 'getLabelFormat',
        'packages' => 'getPackages',
        'documents' => 'getDocuments',
        'documentFormat' => 'getDocumentFormat'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['consignmentShipmentId'] = isset($data['consignmentShipmentId']) ? $data['consignmentShipmentId'] : null;
        $this->container['consignmentTrackingNumber'] = isset($data['consignmentTrackingNumber']) ? $data['consignmentTrackingNumber'] : null;
        $this->container['consignmentCarrierTrackingUrl'] = isset($data['consignmentCarrierTrackingUrl']) ? $data['consignmentCarrierTrackingUrl'] : null;
        $this->container['labels'] = isset($data['labels']) ? $data['labels'] : null;
        $this->container['labelFormat'] = isset($data['labelFormat']) ? $data['labelFormat'] : null;
        $this->container['packages'] = isset($data['packages']) ? $data['packages'] : null;
        $this->container['documents'] = isset($data['documents']) ? $data['documents'] : null;
        $this->container['documentFormat'] = isset($data['documentFormat']) ? $data['documentFormat'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets consignmentShipmentId
     *
     * @return string
     */
    public function getConsignmentShipmentId()
    {
        return $this->container['consignmentShipmentId'];
    }

    /**
     * Sets consignmentShipmentId
     *
     * @param string $consignmentShipmentId Consignment Shipment Id <br />Only populated if the service is a consignment service.
     *
     * @return $this
     */
    public function setConsignmentShipmentId($consignmentShipmentId)
    {
        $this->container['consignmentShipmentId'] = $consignmentShipmentId;

        return $this;
    }

    /**
     * Gets consignmentTrackingNumber
     *
     * @return string
     */
    public function getConsignmentTrackingNumber()
    {
        return $this->container['consignmentTrackingNumber'];
    }

    /**
     * Sets consignmentTrackingNumber
     *
     * @param string $consignmentTrackingNumber Consignment Tracking Number <br />Only populated if the service is a consignment service
     *
     * @return $this
     */
    public function setConsignmentTrackingNumber($consignmentTrackingNumber)
    {
        $this->container['consignmentTrackingNumber'] = $consignmentTrackingNumber;

        return $this;
    }

    /**
     * Gets consignmentCarrierTrackingUrl
     *
     * @return string
     */
    public function getConsignmentCarrierTrackingUrl()
    {
        return $this->container['consignmentCarrierTrackingUrl'];
    }

    /**
     * Sets consignmentCarrierTrackingUrl
     *
     * @param string $consignmentCarrierTrackingUrl Consignment Carrier Tracking URL <br />Only populated if the service is a consignment service and is available
     *
     * @return $this
     */
    public function setConsignmentCarrierTrackingUrl($consignmentCarrierTrackingUrl)
    {
        $this->container['consignmentCarrierTrackingUrl'] = $consignmentCarrierTrackingUrl;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return string
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param string $labels Labels <br />Populated if requested Action was 'Process'
     *
     * @return $this
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets labelFormat
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormat
     */
    public function getLabelFormat()
    {
        return $this->container['labelFormat'];
    }

    /**
     * Sets labelFormat
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailLabelFormat $labelFormat labelFormat
     *
     * @return $this
     */
    public function setLabelFormat($labelFormat)
    {
        $this->container['labelFormat'] = $labelFormat;

        return $this;
    }

    /**
     * Gets packages
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentResponseCarrierSpecificsPackageResponse[]
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailShipmentResponseCarrierSpecificsPackageResponse[] $packages Packages <br />The details of each package.
     *
     * @return $this
     */
    public function setPackages($packages)
    {
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Gets documents
     *
     * @return string
     */
    public function getDocuments()
    {
        return $this->container['documents'];
    }

    /**
     * Sets documents
     *
     * @param string $documents Customs Documents <br />Populated if requested Action was 'Process' and shipment is dutiable
     *
     * @return $this
     */
    public function setDocuments($documents)
    {
        $this->container['documents'] = $documents;

        return $this;
    }

    /**
     * Gets documentFormat
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\DocumentFormat
     */
    public function getDocumentFormat()
    {
        return $this->container['documentFormat'];
    }

    /**
     * Sets documentFormat
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\DocumentFormat $documentFormat documentFormat
     *
     * @return $this
     */
    public function setDocumentFormat($documentFormat)
    {
        $this->container['documentFormat'] = $documentFormat;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
