<?php
/**
 * RoyalMailViewShippingAccountLocationShippingLocationForAccount
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMailV4\ShipmentsApi\Model;

use \ArrayAccess;
use \RoyalMailV4\ShipmentsApi\ObjectSerializer;

/**
 * RoyalMailViewShippingAccountLocationShippingLocationForAccount Class Doc Comment
 *
 * @category Class
 * @description Shipping Location &lt;br /&gt;A location where the shipping account sends shipments from. &lt;br /&gt;Every Shipping Account must have at least one Shipping Location. &lt;br /&gt;A shipping account can have lots of shipping locations. &lt;br /&gt;Each shipment created must be from an existing shipping location.
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailViewShippingAccountLocationShippingLocationForAccount implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailViewShippingAccountLocationShippingLocationForAccount';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shippingLocationId' => 'string',
        'locationAlias' => 'string',
        'carrierSpecifics' => '\RoyalMailV4\ShipmentsApi\Model\RoyalMailViewShippingAccountLocation',
        'timezone' => 'string',
        'lastUpdatedDateUtc' => '\DateTime',
        'lastUpdatedBy' => 'string',
        'address' => '\RoyalMailV4\ShipmentsApi\Model\ShippingLocationAddress'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shippingLocationId' => 'uuid',
        'locationAlias' => null,
        'carrierSpecifics' => null,
        'timezone' => null,
        'lastUpdatedDateUtc' => 'date-time',
        'lastUpdatedBy' => null,
        'address' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shippingLocationId' => 'ShippingLocationId',
        'locationAlias' => 'LocationAlias',
        'carrierSpecifics' => 'CarrierSpecifics',
        'timezone' => 'Timezone',
        'lastUpdatedDateUtc' => 'LastUpdatedDateUtc',
        'lastUpdatedBy' => 'LastUpdatedBy',
        'address' => 'Address'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shippingLocationId' => 'setShippingLocationId',
        'locationAlias' => 'setLocationAlias',
        'carrierSpecifics' => 'setCarrierSpecifics',
        'timezone' => 'setTimezone',
        'lastUpdatedDateUtc' => 'setLastUpdatedDateUtc',
        'lastUpdatedBy' => 'setLastUpdatedBy',
        'address' => 'setAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shippingLocationId' => 'getShippingLocationId',
        'locationAlias' => 'getLocationAlias',
        'carrierSpecifics' => 'getCarrierSpecifics',
        'timezone' => 'getTimezone',
        'lastUpdatedDateUtc' => 'getLastUpdatedDateUtc',
        'lastUpdatedBy' => 'getLastUpdatedBy',
        'address' => 'getAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shippingLocationId'] = isset($data['shippingLocationId']) ? $data['shippingLocationId'] : null;
        $this->container['locationAlias'] = isset($data['locationAlias']) ? $data['locationAlias'] : null;
        $this->container['carrierSpecifics'] = isset($data['carrierSpecifics']) ? $data['carrierSpecifics'] : null;
        $this->container['timezone'] = isset($data['timezone']) ? $data['timezone'] : null;
        $this->container['lastUpdatedDateUtc'] = isset($data['lastUpdatedDateUtc']) ? $data['lastUpdatedDateUtc'] : null;
        $this->container['lastUpdatedBy'] = isset($data['lastUpdatedBy']) ? $data['lastUpdatedBy'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shippingLocationId'] === null) {
            $invalidProperties[] = "'shippingLocationId' can't be null";
        }
        if ($this->container['locationAlias'] === null) {
            $invalidProperties[] = "'locationAlias' can't be null";
        }
        if ($this->container['carrierSpecifics'] === null) {
            $invalidProperties[] = "'carrierSpecifics' can't be null";
        }
        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        if ($this->container['lastUpdatedDateUtc'] === null) {
            $invalidProperties[] = "'lastUpdatedDateUtc' can't be null";
        }
        if ($this->container['lastUpdatedBy'] === null) {
            $invalidProperties[] = "'lastUpdatedBy' can't be null";
        }
        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shippingLocationId
     *
     * @return string
     */
    public function getShippingLocationId()
    {
        return $this->container['shippingLocationId'];
    }

    /**
     * Sets shippingLocationId
     *
     * @param string $shippingLocationId Shipping Location Id <br />The system identifier for this shipping location.
     *
     * @return $this
     */
    public function setShippingLocationId($shippingLocationId)
    {
        $this->container['shippingLocationId'] = $shippingLocationId;

        return $this;
    }

    /**
     * Gets locationAlias
     *
     * @return string
     */
    public function getLocationAlias()
    {
        return $this->container['locationAlias'];
    }

    /**
     * Sets locationAlias
     *
     * @param string $locationAlias Shipping Location Alias <br />Your identifier for this shipping location. Must be unique.
     *
     * @return $this
     */
    public function setLocationAlias($locationAlias)
    {
        $this->container['locationAlias'] = $locationAlias;

        return $this;
    }

    /**
     * Gets carrierSpecifics
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\RoyalMailViewShippingAccountLocation
     */
    public function getCarrierSpecifics()
    {
        return $this->container['carrierSpecifics'];
    }

    /**
     * Sets carrierSpecifics
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\RoyalMailViewShippingAccountLocation $carrierSpecifics carrierSpecifics
     *
     * @return $this
     */
    public function setCarrierSpecifics($carrierSpecifics)
    {
        $this->container['carrierSpecifics'] = $carrierSpecifics;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone Time zone
     *
     * @return $this
     */
    public function setTimezone($timezone)
    {
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets lastUpdatedDateUtc
     *
     * @return \DateTime
     */
    public function getLastUpdatedDateUtc()
    {
        return $this->container['lastUpdatedDateUtc'];
    }

    /**
     * Sets lastUpdatedDateUtc
     *
     * @param \DateTime $lastUpdatedDateUtc Last Updated Date UTC
     *
     * @return $this
     */
    public function setLastUpdatedDateUtc($lastUpdatedDateUtc)
    {
        $this->container['lastUpdatedDateUtc'] = $lastUpdatedDateUtc;

        return $this;
    }

    /**
     * Gets lastUpdatedBy
     *
     * @return string
     */
    public function getLastUpdatedBy()
    {
        return $this->container['lastUpdatedBy'];
    }

    /**
     * Sets lastUpdatedBy
     *
     * @param string $lastUpdatedBy Last Updated By
     *
     * @return $this
     */
    public function setLastUpdatedBy($lastUpdatedBy)
    {
        $this->container['lastUpdatedBy'] = $lastUpdatedBy;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \RoyalMailV4\ShipmentsApi\Model\ShippingLocationAddress
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \RoyalMailV4\ShipmentsApi\Model\ShippingLocationAddress $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
