<?php
/**
 * ShipmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace RoyalMailV4\ShipmentsApi;

use RoyalMailV4\ShipmentsApi\Configuration;
use RoyalMailV4\ShipmentsApi\ApiException;
use RoyalMailV4\ShipmentsApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ShipmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  RoyalMailV4\ShipmentsApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShipmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v4ShipmentsDeferPut
     *
     * Defer Shipments.
     *
     */
    public function testV4ShipmentsDeferPut()
    {
    }

    /**
     * Test case for v4ShipmentsPreallocateTrackingNumberRmPost
     *
     * Pre Allocate Tracking Number.
     *
     */
    public function testV4ShipmentsPreallocateTrackingNumberRmPost()
    {
    }

    /**
     * Test case for v4ShipmentsPrintDocumentCarrierCodeShipmentIdPost
     *
     * Print Document.
     *
     */
    public function testV4ShipmentsPrintDocumentCarrierCodeShipmentIdPost()
    {
    }

    /**
     * Test case for v4ShipmentsPrintLabelRmShipmentIdGet
     *
     * Print Label.
     *
     */
    public function testV4ShipmentsPrintLabelRmShipmentIdGet()
    {
    }

    /**
     * Test case for v4ShipmentsPrintMyLabelQRCodeRmShipmentIdGet
     *
     * Print My Label QR Code.
     *
     */
    public function testV4ShipmentsPrintMyLabelQRCodeRmShipmentIdGet()
    {
    }

    /**
     * Test case for v4ShipmentsRmPost
     *
     * Create Shipment.
     *
     */
    public function testV4ShipmentsRmPost()
    {
    }

    /**
     * Test case for v4ShipmentsShippingLocationIdGet
     *
     * Get Shipments.
     *
     */
    public function testV4ShipmentsShippingLocationIdGet()
    {
    }

    /**
     * Test case for v4ShipmentsStatusPut
     *
     * Update Status.
     *
     */
    public function testV4ShipmentsStatusPut()
    {
    }
}
